import requests
import os

from dotenv import load_dotenv

load_dotenv()

# SAP HCM API credentials
client_id = os.getenv("SAP_HR_API_CLIENT_ID") 
client_secret = os.getenv("SAP_HR_API_CLIENT_SECRET") 
bu_sap_system_id = os.getenv("BU_SAP_SYSTEM_ID") 


headers = {'Content-Type': 'application/json',  
           'client-id': client_id,
           'client-secret': client_secret}

url = "you SAP HR API endpoint"


def retrieve_employee_data(user_email):
    """
    Retrieves employee data from the SAP Human Capital Management (HCM) API using the user's email.

    The function sends a GET request to the SAP HCM API. It specifies the user's email address as a parameter along with 
    other required headers, such as the client ID, client secret, and the business unit SAP system ID. The response from 
    the API is then processed to extract key employee information.

    Args:
        user_email (str): The email address of the user whose employee data is to be retrieved.

    Returns:
        dict: A dictionary containing the employee's details, including:
              - FirstName: The first name of the employee.
              - LastName: The last name of the employee.
              - CompanyEmailAddress: The company email address of the employee.
              - TINNumber: The Tax Identification Number of the employee.
              - SSSNumber: The Social Security System Number of the employee.
              - PhilHealthNumber: The PhilHealth Insurance Number of the employee.
              - PAGIBIGNumber: The PAGIBIG Fund Number of the employee.
              - EmergencyContact: The emergency contact details of the employee.
              - BusinessUnit: The business unit to which the employee belongs.
    """
    # NOTE: docstrings generated by ChatGPT

    response = requests.get(url = url, 
                            headers = headers,
                            params = {'field' : 'perner',
                                  'value' : user_email,
                                  'systemId' : bu_sap_system_id})
                                   
    container = response.json()
    return {
    
    'FirstName': container['FirstName'], 
    'LastName': container['LastName'], 
    'CompanyEmailAddress': container['CompanyEmailAddress'],
    'TINNumber': container['TINNumber'], 
    'SSSNumber': container['SSSNumber'], 
    'PhilHealthNumber': container['PhilHealthNumber'], 
    'PAGIBIGNumber': container['PAGIBIGNumber'], 
    'EmergencyContact': container['EmergencyContact'], 
    'BusinessUnit': container['BusinessUnit'], 
    }