import requests
import os

# ServiceNow API credentials

client_id = os.getenv("SERVICENOW_API_CLIENT_ID")
client_secret = os.getenv("SERVICENOW_API_CLIENT_SECRET")

headers = {'client-id': client_id, 
           'client-secret': client_secret}
          
def get_ticket_info(incident_no, source_incident_id):
    """
    Retrieves detailed information about a specific ServiceNow ticket using its incident number and source incident ID.

    The function sends a GET request to the ServiceNow API with the incident number and source incident ID as parameters.
    It extracts information from the API response and formats it into a dictionary. This includes the incident number, 
    description, current status, assigned group, last updated timestamp, work notes, and the close reason of the incident.

    Args:
        incident_no (str): The incident number of the ServiceNow ticket.
        source_incident_id (str): The source incident ID associated with the ServiceNow ticket.

    Returns:
        dict: A dictionary containing detailed information about the ServiceNow ticket, including:
              - Incident No: The incident number.
              - Description: A description of the incident.
              - Status: The current status of the incident.
              - Group Assigned: The group assigned to the incident.
              - Last Updated: The timestamp of the last update.
              - Work Notes: Notes related to the work done on the incident.
              - Close Reason: The reason for closing the incident, if applicable.    
    """
    # NOTE: docstrings generated by ChatGPT

    response = requests.get(url = f"your.servicenow.api.incident-no={incident_no}&source-incident-id={source_incident_id}",
                            headers = headers,)                          
                                   
    container = response.json()    
    return {

    'Incident No': container['data']['incidentNo'],
    'Description': container['data']['description'],
    'Status': container['data']['state'],
    'Group Assigned': container['data']['assignmentGroup'],
    'Last Updated': container['data']['lastUpdatedOn'],
    'Work Notes': container['data']['workNote'],
    'Close Reason': container['data']['closeNote'],
    }